[phases.setup]
aptPkgs = ['libsqlite3-0', 'sqlite3']
nixPkgs = ['python-3.10', 'sqlite']  # اطمینان از Python 3.10 و SQLite

[phases.install]
cmds = ['pip install -r requirements.txt']  # نصب پکیج‌های پایتون

[phases.build]
cmds = ['echo "Build phase completed"']  # اختیاری: تأیید بیلد

[start]
cmd = 'python telegram_bot.py'  # اجرای ربات